www:
  build: images/www
  links:
    - db:mysql
  ports:
    - 80:80
    - 443:443
  volumes:
    - "./wwwhtml:/var/www/html"
db:
  image: mysql
  volumes:
    - "./libmysql:/var/lib/mysql"
  environment:
    MYSQL_ROOT_PASSWORD: mySecretMySQLPassword